services:
  penpot-backend:
    image: penpotapp/backend:latest
    container_name: penpot-backend
    environment:
      - PENPOT_PUBLIC_URI=http://localhost:9001
      - PENPOT_FLAGS=enable-registration
      - PENPOT_DATABASE_URI=postgresql://penpot:penpot@penpot-db/penpot
      - PENPOT_REDIS_URI=redis://penpot-redis
    depends_on:
      - penpot-db
      - penpot-redis
    networks:
      - penpot-network

  penpot-frontend:
    image: penpotapp/frontend:latest
    container_name: penpot-frontend
    environment:
      - PENPOT_PUBLIC_URI=http://localhost:9001
    depends_on:
      - penpot-backend
    ports:
      - "9001:80"
    networks:
      - penpot-network

  penpot-db:
    image: postgres:15
    container_name: penpot-db
    environment:
      POSTGRES_USER: penpot
      POSTGRES_PASSWORD: penpot
      POSTGRES_DB: penpot
    volumes:
      - penpot_db_data:/var/lib/postgresql/data
    networks:
      - penpot-network

  penpot-redis:
    image: redis:7
    container_name: penpot-redis
    networks:
      - penpot-network

networks:
  penpot-network:

volumes:
  penpot_db_data:
